title: Alejandra Alava
logo : /images/cv pic.jpeg
description: Technical Skills -> C#, Python, PHP, JavaScript, TypeScript, .NET Entity Framework, Django, Flask, Laravel, Node.js, React, Automation Anywhere, UiPath, SQL (MySQL, PostgreSQL, DB2).
show_downloads: true
theme: jekyll-theme-minimal
