title: Alejandra Alava
logo: /images/cv pic.jpeg
description: As a Mechatronics Engineer, I possess a fervent enthusiasm for programming, electronics, and technology.  I am eager to contribute to a professional environment where I can apply my skills, take on new challenges, and continue learning.
show_downloads: true
theme: jekyll-theme-minimal
